defaults: &defaults
  options:
    raise_not_found_error: false
    skip_version_check: true

development:
  <<: *defaults
  sessions:
    default:
      database: eurucamp_activities
      hosts:
        - localhost:27017

test:
  <<: *defaults
  sessions:
    default:
      database: eurucamp_activities_test
      hosts:
        - localhost:27017

production:
  <<: *defaults
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        safe: false # no idea why i can't set it to true
