defaults: &defaults
  twitter:
    account: "Eactivitiestest"
    tokens:
      im_in: "#imin"
      im_out: "#imout"
  activities:
    -
      name: "Football game"
      code: "FTB"
      when: 2012-08-17 20:00:00 +0100
      where: "Blah"
    -
      name: "Drinkup"
      code: "DRN"
      when: 2012-08-18 20:00:00 +0100
      where: "Blah"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
