defaults: &defaults
  twitter:
    account: "your-account-development"
    messages:
      in: "great, see you there!"
      out: "participation removed!"
    tokens:
      im_in: "imin"
      im_out: "imout"

development:
  <<: *defaults

test:
  twitter:
    account: "your-account-test"
    messages:
      in: "great, see you there!"
      out: "participation removed!"
    tokens:
      im_in: "imin"
      im_out: "imout"

production:
  <<: *defaults
  twitter:
    account: "your-account"
    messages:
      in: "great, see you there!"
      out: "participation removed!"
    tokens:
      im_in: "imin"
      im_out: "imout"
