defaults: &defaults
  twitter:
    account: "Eactivitiestest"
    tokens:
      im_in: "#imin"
      im_out: "#imout"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
