defaults: &defaults
  twitter:
    account: "Eactivitiestest"
    messages:
      in: "great, see you there!"
      out: "participation removed!"
    tokens:
      im_in: "imin"
      im_out: "imout"

development:
  <<: *defaults

test:
  twitter:
    account: "eurucamplivetest"
    messages:
      in: "great, see you there!"
      out: "participation removed!"
    tokens:
      im_in: "imin"
      im_out: "imout"

production:
  <<: *defaults
  twitter:
    account: "eurucamplive"
    messages:
      in: "great, see you there!"
      out: "participation removed!"
    tokens:
      im_in: "imin"
      im_out: "imout"
