defaults: &defaults
  options:
    raise_not_found_error: false

development:
  <<: *defaults
  sessions:
    default:
      database: eurucamp_activities
      hosts:
        - localhost:27017

test:
  <<: *defaults
  sessions:
    default:
      database: eurucamp_activities_test
      hosts:
        - localhost:27017

production:
  <<: *defaults
  sessions:
    uri: <%= ENV['MONGOHQ_URL'] %>
    options:
      skip_version_check: true
      safe: true

  sessions:
    default:
      hosts:
        - - <hostname>.member0.mongohq.com
          - <port_number>
        - - <hostname>.member1.mongohq.com
          - <port_number>
      username: <username>
      password: <password>
      database: <database>
      options:
        skip_version_check: true
        safe: true