defaults: &defaults
  options:
    raise_not_found_error: false

development:
  <<: *defaults
  sessions:
    default:
      database: eurucamp_activities
      hosts:
        - localhost:27017

test:
  <<: *defaults
  sessions:
    default:
      database: eurucamp_activities_test
      hosts:
        - localhost:27017

production:
  <<: *defaults
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
